[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/GeertJohan/go.incremental"

[[constraint]]
  name = "github.com/akavel/rsrc"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/daaku/go.zipexe"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/osext"
